Repository selsa-inube/inubekit-countdownbar, pull requests merged in 2024-03, with the labels that each got.

#3 Refactor component to use new token structure
  package-lock.json
  package.json
  src/CountdownBar/CountdownBar.stories.tsx
  src/CountdownBar/index.tsx
  src/CountdownBar/props.ts
  src/CountdownBar/styles.js
  vite.config.ts
Labels: major

#4 Release new version 2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#5 Implement try..catch in props of type function
  src/CountdownBar/index.tsx
  src/CountdownBar/styles.js
Labels: minor

#6 Publish new version 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#7 Update inubekit/countdownbar to storybook v8
  package-lock.json
  package.json
Labels: dependencies

#8 Adjust and export interfaces
  src/CountdownBar/index.tsx
  src/CountdownBar/props.ts
  src/index.ts
Labels: minor

#9 Publish new version 2.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
